### ISSUE TITLE
Uncaught ReflectionException: Class "Hybrid\View\Contracts\View"

### ISSUE THREAD

**Issue by redactuk** [themehybrid/hybrid-view#9]
Hello

I'm trying to upgrade a barebones template to use HC 7.x and modular system.

Currently nothing else is setup other than to display a simple header, content and footer view.
With the theme applied, accessing home page of the site gives me error:

```
Fatal error: Uncaught ReflectionException: Class "Hybrid\View\Contracts\View" does not exist in C:\laragon\www\dev4\wp-content\themes\rscustom\vendor\themehybrid\hybrid-core\src\Container\Container.php:933
```

composer.json:
```
	"composer/installers": "~1.0",
    "themehybrid/hybrid-core": "^7.0",
	"themehybrid/hybrid-attr": "^1.0",
	"themehybrid/hybrid-contracts": "^2.0",
    "themehybrid/hybrid-template": "^1.0",
    "themehybrid/hybrid-template-hierarchy": "^1.0",
	"themehybrid/hybrid-template-manager": "^1.0",
    "themehybrid/hybrid-theme": "^2.0",
    "themehybrid/hybrid-view": "^2.0"
  },
```

My AppServiceProvider:

```
namespace RSCustom\Providers;

use Hybrid\Core\ServiceProvider;
use Hybrid\View\Contracts\Engine as EngineContract;
use Hybrid\View\Contracts\View as ViewContract;

class AppServiceProvider extends ServiceProvider
{
	/**
	 * Callback executed when the `\Hybrid\Core\Application` class registers
	 * providers. Use this method to bind items to the container.
	 *
	 * @return void
	 */
	public function register(): void
	{
		// Create aliases for the view and engine.
		$this->app->alias(ViewContract::class, 'view');
		$this->app->alias(EngineContract::class, 'view/engine');

		// Bind the Laravel Mix manifest for cache-busting.
		$this->app->singleton('rscustom/mix', function () {

			$file = get_theme_file_path('public/mix-manifest.json');

			return file_exists($file) ? json_decode(file_get_contents($file), true) : null;
		});
	}
}
```

However, both:

```
use Hybrid\View\Contracts\Engine as EngineContract;
use Hybrid\View\Contracts\View as ViewContract;
```

are reported in my editor as undefined namespace and class.

my root resources/views/index.php:

```
// Load header/* template.
Hybrid\View\display( 'header', Hybrid\Template\Hierarchy\hierarchy() );

// Load content/* template.
Hybrid\View\display( 'content', Hybrid\Template\Hierarchy\hierarchy() );

// Load footer/* template.
Hybrid\View\display( 'footer', Hybrid\Template\Hierarchy\hierarchy() );

```

Possibly a separate issue, but in previous versions I used:
Hybrid\View\display( 'footer', Hybrid\Template\hierarchy() );

this now reports 'undefined function'?

I have default templates set up for header, content and footer.

Any help appreciated.

**Comment by redactuk** [comment]
ok so maybe I should be using
```php
use Hybrid\Theme\View\Legacy\Contracts\Engine as EngineContract;
use Hybrid\Theme\View\Legacy\Contracts\View as ViewContract;
``` 
however now I get:
Uncaught Hybrid\Contracts\Container\BindingResolutionException: Target [Hybrid\Contracts\View\Factory] is not instantiable

wish you guys could just add the toniest bit of documentation as to how to use hybrid-core v6 onwards :(

**Comment by redactuk** [comment]
Can someone please show me how this works with v2? teating my hair out here. 
Just a tiny bit of documentation would be appreciated :(

**Comment by saas786** [comment]
@redactuk 
I missed your initial comment. If you're interested, I can update the Exhale theme so you can learn from it. I am currently working on making HC, its addons, and dependencies prefixed. This ensures that we can use it safely without conflicting with other plugins or themes. You'll be able to use it without a prefix if your website doesn't have any conflicting dependencies (using Composer), or with a prefix if you prefer. However, a quicker solution would be to take a look at your code and provide a solution accordingly.

Integrating https://github.com/humbug/php-scoper for prefixing.

Successfully used it for a plugin and a theme; it worked fine.

**Comment by redactuk** [comment]
@saas786 updating Exhale would be very useful. 

I actually already checked that out and saw you had pull request from 2021 to bump to HC v6, but that left me even more confused as you were using:
```
use Hybrid\Theme\View\Legacy\Contracts\Engine as EngineContract;
use Hybrid\Theme\View\Legacy\Contracts\View as ViewContract;
```

I've been using HC v5 for many years for client themes, and I'm familiar with most of it. I had many bookmarks to Hybrid website articles explaining how the new modulear system works in v6+ but sadly that site is no longer up. My goal currently is simply to update my base client theme to use HC v7 to enable PHP 8.1 compatibility.

**Comment by saas786** [comment]
@redactuk 

Yes, the legacy view system is now moved to the hybrid-theme package/addon, while hybrid-view v2 utilizes the Laravel view package.

No, prefixing is not for HC code itself (depends on your usage) but rather for its composer dependencies, as they can conflict with other plugins using composer with the same dependencies.

**Comment by saas786** [comment]
hybrid-view v2 will require changing your /views code as well,
I would suggest you should utilize `hybrid-theme`

`"themehybrid/hybrid-theme": "^2.0"` : https://github.com/saas786/exhale/blob/3.0/composer.json#L36

and 

https://github.com/saas786/exhale/blob/3.0/app/bootstrap-app.php#L55

```php
$exhale->provider( \Hybrid\Template\Hierarchy\Provider::class );
$exhale->provider( \Hybrid\Template\Manager\Provider::class );
$exhale->provider( \Hybrid\Theme\View\Legacy\Provider::class );
$exhale->provider( \Hybrid\Theme\Provider::class );
```

https://github.com/saas786/exhale/blob/3.0/app/Provider.php#L46

```php
use Hybrid\Theme\View\Legacy\Contracts\Engine as EngineContract;
use Hybrid\Theme\View\Legacy\Contracts\View as ViewContract;

....

// Create aliases for the view and engine.
$this->app->alias( ViewContract::class, 'view' );
$this->app->alias( EngineContract::class, 'view/engine' );
```

**Comment by redactuk** [comment]
@saas786 ok, doing that gives me:
```
[20-Dec-2023 12:20:50 UTC] PHP Fatal error:  Uncaught Hybrid\Contracts\Container\BindingResolutionException: Target [Hybrid\Contracts\View\Factory] is not instantiable. in C:\laragon\www\wpdev6\wp-content\themes\rscustom\vendor\themehybrid\hybrid-core\src\Container\Container.php:1151
Stack trace:
#0 C:\laragon\www\wpdev6\wp-content\themes\rscustom\vendor\themehybrid\hybrid-core\src\Container\Container.php(942): Hybrid\Container\Container->notInstantiable('Hybrid\\Contract...')
#1 C:\laragon\www\wpdev6\wp-content\themes\rscustom\vendor\themehybrid\hybrid-core\src\Container\Container.php(400): Hybrid\Container\Container->build('Hybrid\\Contract...')
#2 C:\laragon\www\wpdev6\wp-content\themes\rscustom\vendor\themehybrid\hybrid-core\src\Core\Application.php(889): Hybrid\Container\Container->resolve('Hybrid\\Contract...', Array, true)
#3 C:\laragon\www\wpdev6\wp-content\themes\rscustom\vendor\themehybrid\hybrid-core\src\Container\Container.php(602): Hybrid\Core\Application->resolve('Hybrid\\Contract...', Array)
#4 C:\laragon\www\wpdev6\wp-content\themes\rscustom\vendor\themehybrid\hybrid-core\src\Core\Application.php(875): Hybrid\Container\Container->make('Hybrid\\Contract...', Array)
#5 C:\laragon\www\wpdev6\wp-content\themes\rscustom\vendor\themehybrid\hybrid-core\src\functions-helpers.php(34): Hybrid\Core\Application->make('Hybrid\\Contract...', Array)
#6 C:\laragon\www\wpdev6\wp-content\themes\rscustom\vendor\themehybrid\hybrid-view\src\functions-helpers.php(31): Hybrid\app('Hybrid\\Contract...')
#7 C:\laragon\www\wpdev6\wp-content\themes\rscustom\vendor\themehybrid\hybrid-view\src\functions-helpers.php(52): Hybrid\View\view('header', Array, Array)
#8 C:\laragon\www\wpdev6\wp-content\themes\rscustom\templates\index.php(8): Hybrid\View\display('header', Array)
#9 C:\laragon\www\wpdev6\wp-includes\template-loader.php(106): include('C:\\laragon\\www\\...')
#10 C:\laragon\www\wpdev6\wp-blog-header.php(19): require_once('C:\\laragon\\www\\...')
#11 C:\laragon\www\wpdev6\index.php(17): require('C:\\laragon\\www\\...')
#12 {main}
  thrown in C:\laragon\www\wpdev6\wp-content\themes\rscustom\vendor\themehybrid\hybrid-core\src\Container\Container.php on line 1151
```

**Comment by redactuk** [comment]
Ok, I got it working: I needed to update my views/index.php

Thanks for you help, much appreciated.

So would there be any advantage to using hybrid-view rather than method you specified above?
Do you have example of how views code would need to be updated?
